# Generated by Django 3.1.6 on 2021-02-16 09:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210206_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Adventure'), ('2', 'Relaxation'), ('3', 'Nature'), ('4', 'Architecture'), ('5', 'Historical'), ('6', 'Religious')], default=('1', 'Adventure'), max_length=11),
        ),
    ]
