# Generated by Django 3.1.6 on 2021-02-20 08:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210217_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Nature', 'Nature'), ('Architecture', 'Architecture'), ('Historical', 'Historical'), ('Religious', 'Religious')], default=(1, 'Adventure'), max_length=61),
        ),
    ]
