# Generated by Django 3.1.6 on 2021-02-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210222_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body2',
            field=models.TextField(blank=True),
        ),
    ]
