# Generated by Django 3.1.6 on 2021-02-17 15:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Adventure'), (2, 'Relaxation'), (3, 'Nature'), (4, 'Architecture'), (5, 'Historical'), (6, 'Religious')], default=(1, 'Adventure'), max_length=11),
        ),
    ]
