# Generated by Django 3.1.6 on 2021-02-20 09:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210217_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Nature', 'Nature'), ('Architecture', 'Architecture'), ('Historical', 'Historical'), ('Religious', 'Religious')], default=(1, 'Adventure'), max_length=61),
        ),
    ]
