# Generated by Django 3.1.6 on 2021-02-22 07:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210220_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Architecture', 'Architecture'), ('Historical', 'Historical'), ('Religious', 'Religious'), ('Educational', 'Educational'), ('Trekking', 'Trekking'), ('Sightseeing', 'Sightseeing'), ('Cultural', 'Cultural'), ('Wildlife', 'Wildlife'), ('One-Day-Trip', 'One-Day-Trip')], default=(1, 'Adventure'), max_length=107),
        ),
    ]
